- lms/djangoapps/courseware/views/views.py
- openedx/core/djangoapps/plugins/plugins_hooks.py
- openedx/features/course_experience/views/course_home.py
Part of the external enrollment integration:
- Allowing custom entry points for courses.
> PAE-291 - Supporting a custom entry point  for courses.

- cms/envs/production.py
Description
---------------
This PR adds SCORMXBLOCK_ASYNC_THRESHOLD for SCORM xblock.
> Add Scorm Xblock setting.

- lms/djangoapps/grades/tasks.py
**Description:**
This PR adds a quick fix for this issue with SGA xblock: https://discuss.openedx.org/t/problems-with-sga-grade-submission/2415
*Related work:*
[PR](https://github.com/proversity-org/edx-platform/pull/1140)
> MIGRATION - Applying Hotfix over SGA graded submissions

- lms/djangoapps/ccx/views.py
This PR migrates the PAE-133 feature intended to exclude main course staff users from the grades download report on the CCX student admin page.
https://github.com/proversity-org/edx-platform/pull/1136
> PAE-133 - Exclude main course staff users from grades download.

- common/lib/capa/capa/capa_problem.py
- common/lib/capa/capa/responsetypes.py
- common/lib/xmodule/xmodule/capa_base.py
**Previous work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1112/files)
> MIGRATION - Allowing "problems" to send a submission so "Recap xblock" can get learners responses.

- lms/djangoapps/instructor/views/instructor_dashboard.py
- lms/static/js/instructor_dashboard/instructor_dashboard.js
- lms/static/js/instructor_dashboard/recap.js
- lms/templates/instructor/instructor_dashboard_2/recap.html
- lms/templates/main.html
This PR adds the instructor interface to explore recaps in a course.
**Previous work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1090)
> MIGRATION  - Adding recap interface as instructor tab.

- cms/envs/production.py
This PR allows to handle configuration variables related to asset upload.
**Previous work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1116)
> MIGRATION - Allowing to modify asset upload settings using environment variables.

- common/lib/xmodule/xmodule/video_module/video_module.py
This PR adds "show captions" as an option to display videos. 
**Related work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1115/)
> MIGRATION - Adding "show captions" option over the video module.

- common/djangoapps/third_party_auth/pipeline.py
- common/djangoapps/third_party_auth/settings.py
- common/djangoapps/third_party_auth/strategy.py
**Description:**
This PR adds the following improvements ovet the TPA pipeline
- Fetching IDP provider settings using the 'slug name' .
- Allows user association at login time with multiple sites.
**Related work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1117)
> Migration - TPA pipeline customization

- cms/djangoapps/contentstore/management/commands/export_olx.py
- cms/envs/analytics_exporter.py
- lms/envs/analytics_exporter.py
- openedx/core/djangoapps/theming/helpers_dirs.py
This PR applies the changes made at https://github.com/edx/edx-platform/pull/24946
These changes are already applied in Koa. We don't need to migrate them.
> PAE-476 - Analytics exporter fixes.

- lms/djangoapps/support/static/support/js/views/certificates.js
- lms/static/js/certificates/views/certificate_whitelist.js
- lms/static/js/courseware/certificates_api.js
- lms/static/js/discovery/views/course_card.js
- lms/static/js/discovery/views/facet.js
- lms/static/js/edxnotes/views/note_group.js
- lms/static/js/edxnotes/views/note_item.js
- lms/static/js/edxnotes/views/tabs/course_structure.js
- lms/static/js/edxnotes/views/tabs/recent_activity.js
- lms/static/js/groups/views/course_cohort_settings_notification.js
- lms/static/js/student_account/views/account_section_view.js
- lms/static/js/verify_student/views/error_view.js
Applying security patch https://github.com/edx/edx-platform/pull/25782 following request by eduNEXT DevOps on Wednesday, December 9.
> IM security fixes

- common/djangoapps/third_party_auth/pipeline.py
- common/djangoapps/third_party_auth/settings.py
- openedx/core/djangoapps/user_authn/views/register.py
> Safer associate by email and Skip email verification

- lms/static/sass/bootstrap/_layouts.scss
- lms/static/sass/bootstrap/_legacy.scss
- lms/static/sass/bootstrap/elements/_pagination.scss
- lms/static/sass/bootstrap/lms-main.scss
- lms/static/sass/features/_bookmarks.scss
- openedx/features/course_bookmarks/templates/course_bookmarks/course-bookmarks.html
- openedx/features/course_bookmarks/views/course_bookmarks.py
Description
---------------
This PR adds the previous work of [#24233](https://github.com/edx/edx-platform/pull/24233).
Ticket JIRA openedx: [INCR-43](https://openedx.atlassian.net/browse/INCR-43)(epic) for additional context.
> [BD-10] [DEPR-65][DEPR-74] Remove pattern library of course_bookmarks.py

- cms/djangoapps/contentstore/views/course.py
This PR adds a run_extension_point call to openedx_external_enrollment function to update the other_course_settings of the current course. More context can be found in this [ticket](https://pearsonadvance.atlassian.net/browse/PAE-604?atlOrigin=eyJpIjoiNWVlMThkOTU5MWQyNGQyMWFlYjU4NTY4MzkyZjM0YzQiLCJwIjoiaiJ9).
> Pearson/PAE-604 - Update other course settings in LMS DB on advanced course settings saved from Studio.

- lms/templates/main.html
This PR adds GTM support for the main file which will be able to insert the GTM snippet from the corresponding site configuration.
Mode context in [PAE-809.](https://pearsonadvance.atlassian.net/browse/PAE-809?atlOrigin=eyJpIjoiM2E0NWI1OGVmMWRjNDU5MGE5NDcyNTU0NDQ3Y2YyMGMiLCJwIjoiaiJ9)
> PAE-809-Adding support of GTM for the lms platform.

- openedx/core/djangoapps/user_authn/views/logout.py
Duplicated: https://github.com/Pearson-Advance/edx-platform/pull/44
> PAE-786 - Add run_extension_point to the logout flow.

- requirements/edx/base.in
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
Upstream fix: https://github.com/edx/edx-platform/pull/27358
> Fixing the py2neo package.

- openedx/core/djangoapps/programs/utils.py
This PR adds support for getting the Programs URL from the site configuration.
> PAE-837 - Get Programs URL from the site settings.

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
Update the lti-consumer-xblock package properly.
> chore: update lti-consumer-xblock source properly.

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
Update the lti-consumer-xblock package properly.
> chore: vue/lti requirements update 3

- requirements/edx/base.in
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
Following [this](https://github.com/Pearson-Advance/edx-enterprise/pull/1), we need to update edx-enterprise requiremente properly.
@Squirrel18
> PAE-119 - Update edx enterprise requirement.

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
This PR upgrades edx-enterprise to: 3.2.14.post2.
This PR is related to: https://github.com/Pearson-Advance/edx-enterprise/pull/2
> PAE-134 - Upgrade edx-enterprise.

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/github.in
- requirements/edx/testing.txt
This PR upgrades edx-enterprise to: 3.2.14.post3.
This PR is related to: https://github.com/Pearson-Advance/edx-enterprise/pull/4
> PADV-175 - Upgrade edx-enterprise.

- .github/workflows/build-push-image-main.yml
- .github/workflows/build-push-image-stage.yml
Duplicate: https://github.com/Pearson-Advance/edx-platform/pull/92
> PADV-377.1 - Change version of the tutor build image action.

- requirements/edx/base.in
- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
This PR changes the edx-sga package to use our custom fork.
"make upgrade" has not been used because it generates requirement issues.
Previous work: https://github.com/Pearson-Advance/edx-platform/pull/3
> PADV-466 - Change edx-sga for our custom version.

- cms/envs/production.py
- lms/envs/production.py
- requirements/edx/base.in
- requirements/edx/base.txt
This PR adds the Sentry integration to our platform.
**Note:** Requirements were updated manually in order to avoid changes in other packages. Our platform already meets the requirements for the sentry version used in this PR.
- https://github.com/Pearson-Advance/edx-platform/blob/0c8ff45cf902734666f051f85ab1aea072ccde4f/requirements/edx/base.txt#L240
- https://github.com/Pearson-Advance/edx-platform/blob/0c8ff45cf902734666f051f85ab1aea072ccde4f/requirements/edx/base.txt#LL39C6-L39C6
Settings are defined here:  https://github.com/Pearson-Advance/edx-deployment-pe/commit/aa7a9fea0d35d35ae4b4c42384656f748b253961
> feat: add sentry integration.

- lms/djangoapps/ccx/views.py
- lms/djangoapps/instructor_analytics/basic.py
https://agile-jira.pearson.com/browse/PADV-512
This ticket will only cover CCX-related features.
Following the [feature migration guidelines](https://docs.google.com/document/d/1CqF10P-ESG24J80z_OR7AGXgBMN4Bq55GAe7vcSuTI8/edit?usp=sharing), we need to migrate some of the custom changes.
> PADV-512 - Migrate CCX-related changes.

- lms/static/js/edxnotes/plugins/llm_summarize.js
This PR aims to fix a frontend bug caused when removing the modal's resize feature was causing issues.
> PADV-1593 fix: revert modal resize removal

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
This PR updates to a newest version our custom edx-sga package dependency.
"make upgrade" has not been used because it generates requirement issues.
Previous work: https://github.com/Pearson-Advance/edx-platform/pull/94
> PADV-1558 Update edx-sga dependency to our newest version

- requirements/edx/development.txt
This PR fixes the edx-sga requirement tag in the development.txt file.
PR related: https://github.com/Pearson-Advance/edx-platform/pull/143
> fix: modify edx-sga version tag.

- cms/envs/common.py
This security patch was got from https://github.com/openedx/edx-platform/commit/4c0623bcbc19703e2e1aad0308add05c87b4731a. The official discussion is: https://discuss.openedx.org/t/upcoming-security-fix-for-edx-platform-on-2024-05-17/13004
> fix: prevent setting user attributes from JWT in Studio

- common/djangoapps/third_party_auth/urls.py
- openedx/core/djangoapps/oauth_dispatch/urls.py
- requirements/edx/base.txt
- requirements/edx/github.in
>[!] This PR requires installation of the [Mobile API Extensions](https://github.com/raccoongang/mobile-api-extensions) platform plugin which implements the main authentication updates.
[Mobile API Extensions](https://github.com/raccoongang/mobile-api-extensions) plugin:
- overrides some auth-related platform URLs;
- implements its API / views for mobile SSO (initialization, redirects);
- stores and exchanges mobile authZ codes for client tokens;
The expected usage flow is the following:
- the Open edX platform is configured as a Service Provider (SAML) and has integration with SAML Identity Provider;
- Learner already has registered on the Open edX platform with the mentioned SSO;
- Learner wants to sign in from the Open edX mobile app with the help of an already configured SSO;
- …
> feat: [RG] mobile SSO (SAML) integration

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
This PR updates to a newest version our custom edx-sga package dependency.
"make upgrade" has not been used because it generates requirement issues.
Previous work: https://github.com/Pearson-Advance/edx-platform/pull/144
> PADV-2022 Update edx-sga dependency

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
This PR updates the `openedx-filters` dependency to version `v0.8.0.post3`.  
The update includes a new public filter that allows the LMS to pass additional contextual parameters into enrollment-related email templates. These parameters include the institution name, contact email, class start date, and support for distinguishing between CCX classes and their parent courses.
- Updated the `openedx-filters` version in `requirements/private.txt`:
openedx-filters @ git+https://github.com/Pearson-Advance/openedx-filters.git@v0.8.0.post3#egg=openedx-filters
> fix: updating openedx-filters tag

- lms/templates/instructor/edx_ace/allowedenroll/email/body.html
- lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
This PR includes  improvements to the email templates used in enrollment communications 
- changes one nested table for a div container 
> PADV-2314 fix: Modify styles to adapt the container of enroll email with the email client

- lms/templates/instructor/edx_ace/allowedenroll/email/body.html
- lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
This PR rollback the div approach to adjust the email width.
- changes one nested table for a div container 
> fix: Modify styles to adapt the container of enroll email with the email client (rollback).

- lms/templates/instructor/edx_ace/allowedenroll/email/body.html
- lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
- openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
This PR applies a replace with divs and manage the 
- Adds a max-width into the main container and applies a margin auto to center it.
> fix: Modify styles to adapt the container of enroll email with the email client (replacing div with tables and manage box-sizing).

- requirements/constraints.txt
- requirements/edx/base.txt
- requirements/edx/development.txt
- https://agile-jira.pearson.com/browse/PADV-2388
This PR updates the dependency of `openedx-events` package our latest version.
> PADV-2388: Update openedx-events dependency
