common/djangoapps/student/models.py
common/djangoapps/student/signals/signals.py

This PR adds 'course_enrollment' object so  'ENROLLMENT_TRACK_UPDATED' signal receivers can have extra context.

Adding parameters for the enrollment signal receivers

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in

This PR: https://github.com/edx/edx-platform/pull/22171 changed the edx-sga version, but since we use a custom version, we need to pin the edx-sga to the GitHub repository instead of using the PyPi version.
We could add this custom requirement to the customer-data and remove edx-sga from the platform, but all devstacks will not have SGA installed by default, so that's why it was decided to pin the custom version directly to the platform.
This PR changes the edx-sga version to a custom version.
"make upgrade" was not used because it generated requirement issues.

PAE-279 - Change edx-sga for a custom version.

---

openedx/core/djangoapps/user_api/accounts/settings_views.py

**Description:**
This PR adds support for field name mapping to the extended profile fields.
Now you can set the display name of the fields using a site configuration setting called: extended_profile_fields_name_mapping
e.g.
```json
"extended_profile_fields_name_mapping":{
"my_extended_profile_field": "My extended profile field display name."
}
```
**Previous work:**
[PR](https://github.com/proversity-org/edx-platform/pull/1121)

MIGRATION - Add support for extended profile fields name mapping

---

common/djangoapps/course_modes/models.py

**Description**
This PR applies a quick fix to prevent the 500 error in the about page of a course. This error happens when the currency configured in the course mode (usd for example) is different to the one configured in PAID_COURSE_REGISTRATION_CURRENCY (gbp for example) for the tenant.
**Related work**
[PR](https://github.com/proversity-org/edx-platform/pull/1127)

MIGRATION - Fix to prevent 500 error when the currency for a course differs from the one configured in Ansible

---

lms/djangoapps/ccx/utils.py
lms/djangoapps/instructor/views/gradebook_api.py

This PR migrates the PAE-124 feature intended to exclude main course staff users from the gradebook page.
https://github.com/proversity-org/edx-platform/pull/1132
https://github.com/proversity-org/edx-platform/pull/1134

PAE-124 - Exclude main course staff members from gradebook.

---

lms/djangoapps/ccx/views.py

This PR migrates the PAE-125 feature intended to exclude main course staff users from the CCX student management list.
https://github.com/proversity-org/edx-platform/pull/1135

PAE-125 - Excluding main course staff users from student management list.

---

lms/djangoapps/instructor_analytics/basic.py

This PR migrates the PAE-142 feature intended to exclude main course staff users from the profile report.
https://github.com/proversity-org/edx-platform/pull/1137

PAE-142 - Filter master course staff members from the profile report.

---

common/djangoapps/student/tasks.py

The account activation email is sent via Celery tasks; Celery worker is not aware of the site, therefore the email templates are not overwritten and the account activation email is sent using the edx-platform template.
This PR takes advantage of the Pearson-Core's asynchronous site context feature to make the account activation email site aware.
Pearson-Core must be installed in order to use this approach. If Pearson-Core is not installed, the platform will use the usual email template.

JP-1 - Making the account activation email site aware.

---

lms/djangoapps/ccx/utils.py
lms/djangoapps/ccx/views.py

This PR adds a feature to allow multiple CCX courses per coach for the same main course. The feature must be enabled at site-level and course-level. If the feature is enabled, it will prevent CCX coaches from being redirected to the CCX course and instead will show the Create CCX Course view to allow the CCX coach to create another CCX for the same main course.
Site-level:
"ALLOW_MULTIPLE_CCX_PER_COACH": true
Course-level:
"allow_multiple_ccx_per_coach": true
This setting must be added as an item to the "other course settings" list.

PAE-351 - Allow multiple CCX courses per coach.

---

lms/djangoapps/ccx/utils.py

This PR changes the behaviour of https://github.com/Pearson-Advance/edx-platform/pull/19 to allow all courses CCX-enabled courses to use the feature to allow multiple CCX course per coach. This PR removes the course-level setting but keeps the site-level setting.
Site-level:
"ALLOW_MULTIPLE_CCX_PER_COACH": true
CCX must be enabled in the course to use this feature.

PAE-351 - Enabling multiple CCXs per coach for all CCX courses.

---

common/djangoapps/student/helpers.py
common/djangoapps/student/tests/test_helpers.py

Description
---------------
This PR adds a setting that enables customizing the default redirect behaviour from the login page. Currently, after login, the user is redirected to /dashboard.
Change from: [#21333](https://github.com/edx/edx-platform/pull/21333)

Add site configuration flag to allow changing redirection after login

---

common/djangoapps/third_party_auth/pipeline.py
common/djangoapps/third_party_auth/settings.py

**Ticket:** PAE-546
Added a new step to the social auth pipeline to enable the auto-link the account with the same email.

Adding safer_associate_by_email step to social auth pipeline

---

cms/djangoapps/contentstore/management/commands/export_olx.py

We are currently using the "export_olx" command through edx-analytics-exporter. This "export_olx" command performs the same steps as the course export function in Studio. For some reason that will be explained later, the course export function in Studio worked and "export_olx" did not. After some debugging time, we found out what the problem was.
In short, the problem was related to the folder where the OLX artefacts are stored.
When the course export function is invoked in Studio, it will eventually get here: https://github.com/Pearson-Advance/edx-platform/blob/pearson-release/juniper.stage/cms/djangoapps/contentstore/tasks.py#L273 that function will call "export_course_to_xml" which is in charge of starting the export process. 
When the "export_olx" command is called, it will eventually …

PAE-476.1 - Rename the "export_olx" artefact directory.

---

common/djangoapps/third_party_auth/pipeline.py

This PR adds a logic in 'user_details_force_sync' pipeline step to generate the full name in case it is not provided by IES IDP.
More context can be found in [this ticket](https://pearsonadvance.atlassian.net/browse/PAE-467?atlOrigin=eyJpIjoiNDhhNWYyZWU5NTAxNDAzZTk0YjhmNjk4ZDcxOTBkNzEiLCJwIjoiaiJ9).

PAE-467 - User fullname generation on IES authentication.

---

common/djangoapps/third_party_auth/pipeline.py

This PR adds a logic in 'user_details_force_sync' pipeline step to generate the full name only for IES IDP.
More context can be found in[ this ticket](https://pearsonadvance.atlassian.net/browse/PAE-467?atlOrigin=eyJpIjoiYWExNWZlZjExYmYzNGU3MWE0YmM2NGYyYWEwMzk2NjQiLCJwIjoiaiJ9).
**Note**. This decision was taken since IES IDP will not provide the fullname attribute.
Also we must configure the IDP's fullname attribute map in this page '/admin/third_party_auth/samlproviderconfig/' like the image below. 
- Full Name Attribute -> 'leave it empty'
- Default Value for Full Name -> 'insert any value. **Do not leave empty**'
x

PAE-467-1 - User fullname generation on IES authentication.

---

.github/workflows/assign_by_path.yml
.github/workflows/dev_deployment.yml
.github/workflows/labeler.yml
.github/workflows/prod_deployment.yml

Adding GitHub workflows with:
labeler actions: to define a size for each PR using a label.
assign by path: to add a DevOps reviewer when the PR has migrations changes.
deployments: to run the Jenkins jobs using Jenkins API.

Adding Github Workflows

---

common/djangoapps/student/models.py

Add TRACK_ALL_ENROLLMENT site configuration to allow MIT multiple enrollments in a single course also added on ENROLLMENT_TRACK_UPDATED signal.
Context can be found on [PAE-628](https://pearsonadvance.atlassian.net/browse/PAE-628?atlOrigin=eyJpIjoiY2JhNGY2YzgzMGMyNGQzM2E0YzlkZjE4ZGVhNDI1YTEiLCJwIjoiaiJ9)

Add TRACK_ALL_ENROLLMENT site configuration on ENROLLMENT_TRACK_UPDATED signal.

---

openedx/core/djangoapps/user_authn/views/logout.py

This PR adds an extension point to the logout flow to execute the IES logout function.
This PR is necessary for this to work: https://github.com/Pearson-Advance/pearson-core/pull/20
**This is a short term implementation and should not be migrated.**

PAE-786 - Add run_extension_point to the logout flow.

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

This is to fix the issue when we run a deployment in a new instance.
"ERROR: Could not find a version that satisfies the requirement py2neo==3.1.2"

fix: udpate dependencies

---

common/djangoapps/third_party_auth/pipeline.py

This PR adds a logic in 'user_details_force_sync' pipeline step to generate the full name in case it is not provided by IES IDP.
More context can be found in [ this ticket](https://pearsonadvance.atlassian.net/browse/PAE-467?atlOrigin=eyJpIjoiYWExNWZlZjExYmYzNGU3MWE0YmM2NGYyYWEwMzk2NjQiLCJwIjoiaiJ9).
**Note**. This decision was taken since IES IDP will not provide the fullname attribute.
Also we must configure the IDP's fullname attribute map in this page '/admin/third_party_auth/samlproviderconfig/' like the image below. 
- Full Name Attribute -> 'leave it empty'
- Default Value for Full Name -> 'insert any value. **Do not leave empty**'

PAE-467 - User fullname generation on IES authentication. 

---

common/djangoapps/student/models.py
lms/envs/production.py

Add TRACK_ALL_ENROLLMENT to site configuration.
The course enrollment signal can always be called if TRACK_ALL_ENROLLMENT is enabled.

Pearson/PAE-628-fb - Change ENROLLMENT_TRACK_UPDATED to site configuration

---

lms/djangoapps/instructor/views/instructor_dashboard.py
lms/static/js/instructor_dashboard/data_download.js

This PR adds the license usage URL with the course_id  to the data download section context, so when rendering the template the new button (Download license usage) will have the URL to trigger the action.
More context about the new button in [PADV-26 in openedx-themes](https://github.com/Pearson-Advance/openedx-themes/pull/186).
More context about the view that will have the logic in [PADV-26 course_operations plugin](https://github.com/Pearson-Advance/course_operations/pull/20).
**Note:** This feature is only for **_pearson-vue-theme_** and when the `PCO_ENABLE_LICENSE_ENFORCEMENT` flag is active in the site settings.

PADV-26 - Add license usage url to the data report context.

---

lms/djangoapps/ccx/views.py

This is a join PR together with https://github.com/Pearson-Advance/course_operations/pull/35. The CustomCourseForEdX is already in the caller function of the extension point, so it is better to just pass it instead of retrieving it again in the called function.
For reference: [PADV-50](https://agile-jira.pearson.com/browse/PADV-50)

PADV-50: persist CustomCourseForEdX in InstitutionCCX.

---

common/templates/student/edx_ace/accountactivation/email/body.html
common/templates/student/edx_ace/accountrecovery/email/body.html
common/templates/student/edx_ace/emailchange/email/body.html
lms/templates/instructor/edx_ace/accountcreationandenrollment/email/body.html
lms/templates/instructor/edx_ace/addbetatester/email/body.html
lms/templates/instructor/edx_ace/allowedenroll/email/body.html
lms/templates/instructor/edx_ace/enrolledunenroll/email/body.html
lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
lms/templates/instructor/edx_ace/removebetatester/email/body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/return_to_course_cta.html
openedx/core/djangoapps/user_authn/templates/user_authn/edx_ace/passwordreset/email/body.html

In summary, we are currently experiencing some issues related to the Mako & Django template loaders and this leads to template issues when sending emails from different sites.
More information on this issue can be found here: https://pearsonadvance.atlassian.net/browse/PAE-342
This PR replaces some of the current email templates in favour of the Pearson-brand templates.
Emails should have this Pearson-branded layout:

PAE-342 - Replacing email templates to avoid issues related to Mako & Django template loaders.

---

openedx/core/djangoapps/site_configuration/middleware.py
openedx/core/djangoapps/site_configuration/tests/test_middleware.py

This PR adds the feature which allows us to override the `LANGUAGE_COOKIE` domain based on the **new-custom**`LANGUAGE_COOKIE_DOMAIN` site configuration. The main goal here is to allow eCommerce to consume this cookie.
The idea of doing so is to set a wider domain for `openedx-language-preference` cookie, in order it can be consumed cross-site within our main domain. Currently, the domain is the specific site, Let's see an example regarding the `LANGUAGE_COOKIE` which we are interested in:
If you are in http://lms.main.localhost:18000 and you change the site language using the language selector, then the `openedx-language-preference` cookie is set with `lms.main.localhost` as domain.
Even though this is the expected behavior, the way this is handled does not allow us to share the cookie …

feat: override openedx-language-preference cookie domain.

---

openedx/core/djangoapps/user_authn/views/registration_form.py

This PR add `run_extension_point` for `registration_form.py` to show Privacy Policy in the message showed in Create an Account for Certiportlearning.

VUE/PADV143 certiportlearning - privacy policy

---

lms/djangoapps/instructor/views/instructor_dashboard.py

A `ccx_coach` of a Master Course, gets the `staff` role over the **CCX** the coach creates from the Master. When a user has the `staff` role, then this instructor is able to see and use the **INSTRUCTOR Tab**, therefore can enroll students within the _**membership section**_. 
The course licensing enrollment process is meant to be exclusively through the **CCX COACH Tab**, where enrollments are subject to be rejected if the license has reached its purchased seats limit. Given that the instructor has the capability to enroll users from the **INSTRUCTOR Tab**, then the license can be circumvented.
This PR is an interim countermeasure against the license enforcement issue. The idea is to hide the _**membership section**_  from the licensed CCX staff users to avoid that the instructors are …

PADV-142 - feat: hide the membership section from licensed CCX staff users. 

---

lms/djangoapps/ccx/utils.py
lms/djangoapps/ccx/views.py

This PR updates the current validation to allow more users than the **owner** of the CCX to see and manage the CCX COACH TAB under the condition that those users must have the `staff` role over the CCX. To accomplish this, a run_extension_point is used `PCO_IS_USER_ALLOWED_TO_ACCESS_CCX_COACH_TAB`, and the function is being added [here](https://github.com/Pearson-Advance/course_operations/pull/106).
To conduct the following test, we'll need to have 3 users, let's label them:
- A global admin as _**admin**_. You may use `edx@example.com`
- An institution administrator as **_Coach_**. Create a regular account and then add it trough the portal as an institution administrator for an institution with licenses.
-  A regular user as **_Invited_**. Create an account.
1. Make sure you install the …

PADV-150 - feat: grant access to the CCX Coach Tab to users with staff role over ccx.

---

lms/djangoapps/ccx/views.py

Once a CCX is created, then the `add_master_course_staff_to_ccx` function is called to add staff and instructor roles on ccx to all the staff and instructors members of master course. This is not convenient for Course Licensing because it is not the desired behavior. Therefore, this PR is intended to change the workflow of the ccx creation to stop the execution of `add_master_course_staff_to_ccx`. The approach taken here is also based on the result of [PADV-158](https://agile-jira.pearson.com/browse/PADV-158) where unlicensed ccx are not meant to be created if the site is using Course Licensing.
1. Set up: Given a Master Course under a license, for which there are at least one staff and one instructor on this master course.
2. Using an InstructorAdministrator, create a CCX from the Master …

PADV-144 - Do not add master course staff users to CCXs.

---

lms/djangoapps/ccx/plugins.py
lms/djangoapps/ccx/views.py

This PR adds the run_extension_point's for the is_institution_admin_and_license function of the course operations plugin [PADV-158 - course-operations](https://github.com/Pearson-Advance/course_operations/pull/105) which validate that both institution admin and licence exist to enable access to the ccx_coach tab.
[PADV-158 - course-operations](https://github.com/Pearson-Advance/course_operations/pull/105)
To test this PR it is necessary to be in the correct branch of the related PR's and then enter
`http://localhost:18000/courses/{master_course}/ccx_coach`, do it for non-admin users and institution admins.

PADV-158 - Add PCO_IS_USER_ALLOWED_TO_CREATE_CCX run_extension_point.

---

lms/djangoapps/ccx/views.py

https://agile-jira.pearson.com/browse/PADV-167
This PR add run_extension_point validation with the setting `PCO_ENABLE_COURSE_LICENSING` to enable or disable that all units will be scheduled based upon the start date of the master course. 
Calling the run_extension_points makes sure that the plugin is installed and the site is configured, because if only the site is configured, then it is not enough to guarantee that course licensing is actaully working, because the plugin may not be installed
- Set `'ENABLE_COURSE_LICENSING'` in site configurations.
- Create CCX from licensed Master Course.
- Enter to CCX Coach tab and thin Schedule tab.
- Verify that units have been added.
- Remove unit and refresh ccx_coach tab and verify the units. the changes should be mantained.
- Verify learner …

PADV-167 - Add PCO_ENABLE_COURSE_LICENSING run_extension_point to schedule all units when creating a CCX.

---

lms/djangoapps/ccx/views.py

https://agile-jira.pearson.com/browse/PADV-58
Add a run_extension_point to aggregate enrollments allowed in context to get enrollments and enrollments allowed and show both enrollments and enrollments allowed in the Student List Management in the CCX coach tab.
- https://github.com/Pearson-Advance/openedx-themes/pull/224
- https://github.com/Pearson-Advance/course_operations/pull/116
- Follow the testing instructions at https://github.com/Pearson-Advance/course_operations/pull/116

PADV-58 - Add 'PCO_GET_PENDING_ENROLLMENTS_FOR_CCX' run_extension_point to aggregate  enrollments allowed in context.

---

lms/djangoapps/ccx/utils.py

**Note:** _This change only is applied for sites where Course Licensing is enable._
As there is no feedback when a CCX Coach enrolls someone in her CCX, the purpose of this PR is to support such feature. Therefore the following type of messages are supported with this change:
**Type - Message - Case**
1. SUCCESS - `'Student [name@mail.com] has been enrolled.'` - If user was already registered.
2. SUCCESS - `'Student [name@mail.com] has been invited.'` - If there was no user associated with the email used at enrollment.
3. FAIL (Already supported) -` License limit of {} reached. There are already {} students enrolled across all classes. Please contact Pearson Vue Support Team at {support_link}`.
As this change is required for Course Operations, then the logic behind supporting feedback …

PADV-141 - feat: support feedback at enrollment section within CCX Coach Tab.

---

lms/djangoapps/ccx/plugins.py
lms/djangoapps/ccx/utils.py
lms/djangoapps/ccx/views.py
lms/djangoapps/instructor/views/instructor_dashboard.py

https://agile-jira.pearson.com/browse/PADV-191
This PR focuses on enabling and disabling the plugin via the `ENABLE_COURSE_LICENSING` site configuration using run_extension_point instead `PCO_ENABLE_LICENSE_ENFORCEMENT`.
- https://github.com/Pearson-Advance/course_operations/pull/123
- Follow the tests steps in https://github.com/Pearson-Advance/course_operations/pull/123.

PADV-191 - Use PCO_ENABLE_COURSE_LICENSING run_extension_point instead PCO_ENABLE_LICENSE_ENFORCEMENT site configuration.

---

openedx/core/djangoapps/plugins/plugins_hooks.py

https://agile-jira.pearson.com/browse/PADV-473
This ticket adds run_extension_point which is the Wrapper function to run any extension point at platform level. This PR was already implemented in https://github.com/Pearson-Advance/edx-platform/pull/1.

PADV-473 - Add function for  Extension Points.

---

.github/workflows/build-push-image-main.yml
.github/workflows/build-push-image-stage.yml

https://agile-jira.pearson.com/browse/PADV-377
This PR changes composite action version due to [tutor-build-image-action](https://github.com/Pearson-Advance/tutor-build-image-action) created a new tag (**v1.0.0**).
- Create a test PR in the edx-platform repository.
- Merge this PR into the target branch.
- Check that the Github Action is triggered by the PR merge event.
- Check the output of the image build creation for any issues or silent issues.
-  When the process is complete, check the Docker Hub Pearson repository and verify that the image has been built (https://hub.docker.com/repository/docker/paops/edxapp/general).
-  Use the image in a local environment to test it out.

PADV-377.1 - Change composite action version in workflows to build and push images

---

lms/djangoapps/ccx/plugins.py
lms/djangoapps/ccx/utils.py
lms/djangoapps/ccx/views.py
lms/djangoapps/instructor/views/instructor_dashboard.py

https://agile-jira.pearson.com/browse/PADV-460
To migrate this plugin correctly, we must follow and apply [the plugin migration guidelines](https://docs.google.com/document/d/1CqF10P-ESG24J80z_OR7AGXgBMN4Bq55GAe7vcSuTI8/edit?usp=sharing) and the documentation created in https://agile-jira.pearson.com/browse/PADV-403.
This ticket add all the features that impact the platform from course_operations.
Follow https://github.com/Pearson-Advance/course_operations/pull/128.

PADV-483 - Migrate extension points related to course-operations.

---

common/djangoapps/third_party_auth/pipeline.py
docs/custom_features_documentation.md
openedx/core/djangoapps/user_authn/views/logout.py

https://agile-jira.pearson.com/browse/PADV-513
This PR aims to migrate the SAML custom features developed in the edx-platform. It includes the full name construction from first name and last name feature and the extension point to remove the session from IES. The TPA features was not included since we decided to move it to another ticket.
For the full name construction
- Configure a SAML idp and a sp in the edx-platform (https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/tpa_integrate_open/tpa_SAML_IdP.html)
- in the idp config leave the field full name attribute blank and set an arbitrary value to the attribute full name default value.
- When creating the account with SAML, be sure that the idp passes the first name and last name …

PADV 513 - Migrate SAML features

---

cms/djangoapps/contentstore/views/course.py

https://agile-jira.pearson.com/browse/PADV-511
This PR aims to migrate the pearson-studio-theme to Olive. This adds the necessary context to the index.html template so the organization dropdown can get the organization list and apply the filter. This PR is related to this other in openedx-themes https://github.com/Pearson-Advance/openedx-themes/pull/241
- Change to the branch vue/PADV-511 in your edx-platform
- Activate the studio_home.enable_global_staff_optimization waffle switch in the studio admin page
- Enable the ORGANIZATION_APP feature in Studio
- You should be able to access the org_names_list variable inside the index.html and should contain a list with the organizations
- To test you can enable the pearson-studio-theme and verify that the dropdown contains the sites created

PADV 511 - Migrate Studio theme

---

common/djangoapps/third_party_auth/views.py
common/templates/student/edx_ace/accountactivation/email/body.html
common/templates/student/edx_ace/accountrecovery/email/body.html
common/templates/student/edx_ace/emailchange/email/body.html
lms/templates/instructor/edx_ace/accountcreationandenrollment/email/body.html
lms/templates/instructor/edx_ace/addbetatester/email/body.html
lms/templates/instructor/edx_ace/allowedenroll/email/body.html
lms/templates/instructor/edx_ace/enrolledunenroll/email/body.html
lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
lms/templates/instructor/edx_ace/removebetatester/email/body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/return_to_course_cta.html
openedx/core/djangoapps/user_authn/tasks.py
openedx/core/djangoapps/user_authn/templates/user_authn/edx_ace/passwordreset/email/body.html
openedx/core/djangoapps/user_authn/views/registration_form.py

https://agile-jira.pearson.com/browse/PADV-514
This PR replaces the default email templates with a Pearson branded ones (due to an issue with themed email templates more context on PAE-342 located in JIRA backup) and adds the Pearson privacy policy extension point to the registration page.
For registration feature:
- Install Pearson core
- Apply the following site configurations
```
{
"REQUIRE_TOS_AND_PRIVACY_POLICY_AT_REGISTRATION": true,
"REGISTRATION_EXTRA_FIELDS": {
"honor_code": "hidden",
"terms_of_service": "required"
}
}
```
- You should now see the custom registration form in the registration page.
For the email templates
- Setup an async worker https://3.basecamp.com/3966315/buckets/12732851/messages/2842731569
- Test sending the corresponding emails and verify the styles are …

PADV 514 - BOM changes or features.

---

common/djangoapps/third_party_auth/views.py
openedx/core/djangoapps/user_authn/tasks.py

https://agile-jira.pearson.com/browse/PADV-514
This PR fixs an error that it appears in the activation email.
For registration feature:
- Install Pearson core
- Apply the following site configurations
```
{
"REQUIRE_TOS_AND_PRIVACY_POLICY_AT_REGISTRATION": true,
"REGISTRATION_EXTRA_FIELDS": {
"honor_code": "hidden",
"terms_of_service": "required"
}
}
```
- You should now see the custom registration form in the registration page.
For the email templates
- Setup an async worker https://3.basecamp.com/3966315/buckets/12732851/messages/2842731569
- Test sending the corresponding emails and verify the styles are applied correctly

PADV 514.1 - BOM changes or features.

---

lms/djangoapps/course_goals/management/commands/goal_reminder_email.py
lms/djangoapps/discussion/views.py
lms/djangoapps/instructor/views/instructor_dashboard.py
lms/djangoapps/verify_student/management/commands/send_verification_expiry_email.py
lms/djangoapps/verify_student/services.py
lms/djangoapps/verify_student/views.py
openedx/core/djangoapps/discussions/url_helpers.py
openedx/core/djangoapps/user_api/accounts/settings_views.py
openedx/features/course_experience/url_helpers.py
openedx/features/learner_profile/views/learner_profile.py

https://agile-jira.pearson.com/browse/PADV-554
This PR aims to make all the URLs that are related to all the currently active MFEs (learning, discussions, gradebook, profile and account) site aware. It adds a configuration_helpers.get_value to every MFE URL so it can get the value from site configuration.
- Checkout edx-platform to this branch
- Create a site and a site configuration containing the name of the setting as a key and the url as the value. Like this:
```    "LEARNING_MICROFRONTEND_URL": "http://site1.learningtest.test",
"WRITABLE_GRADEBOOK_URL": "http://site1.gradebooktest.test",
"PROFILE_MICROFRONTEND_URL": "http://site1.profiletest.test",
"ACCOUNT_MICROFRONTEND_URL": "http://site1.accounttest.test",
"DISCUSSIONS_MICROFRONTEND_URL": "http://site1.discussiontest.test"
```
- …

PADV 554 - MFE URLs site aware.

---

openedx/features/enterprise_support/api.py

https://agile-jira.pearson.com/browse/PADV-549
After the enterprise migration https://agile-jira.pearson.com/browse/PADV-489, it was found that when an enterprise customer has data sharing consent enabled and enterprise-catalog is not enabled, the URL where a new enterprise enrollment is directed leads nowhere. Therefore, in this PR the option to redirect to the enterprise-catalog is disabled and it must be redirected to the expected URL, behavior that we currently have in Juniper, through a site configuration called `DISABLE_DATA_SHARING_CONSENT`.
This PR is created to completely disable data sharing consent from enterprise. Following this PR https://github.com/Pearson-Advance/edx-enterprise/pull/8 and https://github.com/Pearson-Advance/edx-enterprise/pull/9, we relized that it's …

PADV-549 - Disable data sharing consent.

---

common/djangoapps/third_party_auth/pipeline.py

This PR allows to associate the edx-platform account with a SAML account under these conditions:
- The platform user's email matches the SAML account email.
- There are not multiple platform accounts with the same email.
- The platform user is not staff or superuser.
- The platform user is active.
This is necessary to prevent users from logging into their edx-platform account to link the SAML IDP account and the edx-platform account.
- Set up a local SAML IDP, check this video about SAML and configuring a local IDP: https://youtu.be/1PoWSVtwheI
- Create a test account on edx-platform.
- Set this feature flag at site level: ASSOCIATE_ACCOUNT_WITH_SAML_IDP_USER
- In a private window, log in using the local IDP and use an account with the same email address as the edx-platform account.
- You …

PADV-516 - Allow platform acount association by email.

---

common/templates/student/edx_ace/accountactivation/email/body.html
common/templates/student/edx_ace/accountrecovery/email/body.html
common/templates/student/edx_ace/emailchange/email/body.html
lms/templates/instructor/edx_ace/accountcreationandenrollment/email/body.html
lms/templates/instructor/edx_ace/addbetatester/email/body.html
lms/templates/instructor/edx_ace/allowedenroll/email/body.html
lms/templates/instructor/edx_ace/enrolledunenroll/email/body.html
lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
lms/templates/instructor/edx_ace/removebetatester/email/body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html
openedx/core/djangoapps/user_authn/templates/user_authn/edx_ace/passwordreset/email/body.html

Overwrote all mylearningx references and removed decorative background images that no longer exist. 
- Start your devstack instance -> `make dev.up`
- Open the email template on  '{DEVSTACK_WORKSPACE}/src/ace_messages/15.20231106-152132.html'

PADV-741: Check Pearson Advance references - pearson-release/olive.stage

---

lms/djangoapps/ccx/views.py
requirements/constraints.txt
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt
xmodule/modulestore/mixed.py
xmodule/modulestore/tests/test_mixed_modulestore.py

This PR adds the ``COURSE_CREATED`` signal in olive version.
1. Use this branch ``vue/PADV-806-course-created`` to use the necessary changes
2. Setup frontend-app-library-authoring if not done before:
```bash
from .devstack import FEATURES
FEATURES['ENABLE_LIBRARY_AUTHORING_MICROFRONTEND'] = True
BLOCKSTORE_API_AUTH_TOKEN = 'edxapp-insecure-devstack-key'
```
3. Set up the blockstore to run in devstack ([ref](https://github.com/openedx/blockstore)) by running the following from the studio shell (make studio-shell):
```bash
./manage.py cms waffle_switch --create blockstore.use_blockstore_app_api on
./manage.py cms shell  # enter python code below
from blockstore.apps.bundles.models import Collection
coll, _ = Collection.objects.get_or_create(title='Devstack Content Collection', …
```

PADV-806: feat: add course created event signals

---

cms/djangoapps/contentstore/signals/handlers.py

Once a course is created in studio the `course_published` signal is emitted, therefore some receivers trigger some async tasks which end up failing because the modulestore can not find the latest data, which resulted in errors related to not being able to find the course, Check this [discussion](https://discuss.openedx.org/t/modulestore-does-not-get-course/10662) for more information and how to replicate those errors. The issue for us comes when working with CCX, this same error raises from time to time when one creates a CCX, therefore the CCX's outline is not generated properly and the course-ware is not showed. Currently it requires that someone manually regenerates the outline at `http://localhost:18000/admin/contentstore/courseoutlineregenerate/`
- Add a delay for …

PADV-794 - fix: delay update_outline_from_modulestore_task after course publish.

---

lms/djangoapps/ccx/views.py

This PR is just to use the ``CCX`` model to use data that is necessary in Skillable Plugin implementation ``GetOrCreateClass``
https://github.com/Pearson-Advance/skillable-plugin/pull/3
Issue: [PADV-815](https://agile-jira.pearson.com/browse/PADV-815)

PADV-815 use the ccx data complete for course created openedx event

---

lms/djangoapps/ccx/views.py

https://agile-jira.pearson.com/browse/PADV-935
Right now, when trying to access the gradebook through the link inside the CCX coach tab, it redirects to the old gradebook rather than the writable gradebook MFE. This PR aims to add the capacity of configuring to which url the gradebook link, in the CCX coach tab, should redirect to.
- Modify CCX coach tab view to edit the gradebook URL.
- Setup devstack.
- Checkout to this branch.
- Configure `WRITABLE_GRADEBOOK_URL` either as a site configuration or a Django setting.
- Enable the `grades.writable_gradebook` waffle flag.
- Create a CCX (licensed or not).
- Go to the CCX Coach tab and inside student admin, the 'View Gradebook' link should point to the URL configured in the settings.

PADV 935 - CCX - replace link to old gradebook with link to new gradebook

---

lms/djangoapps/courseware/module_render.py
lms/djangoapps/courseware/tests/test_module_render.py

This change fixes a moderate security in edx-platform.
The original description is [here](https://discuss.openedx.org/t/upcoming-moderate-security-fix-for-edx-platform-on-2024-01-12/12063).
Source commit: https://github.com/openedx/edx-platform/pull/34047
Nuez reference by eduNEXT: https://github.com/eduNEXT/edunext-platform/pull/794

fix: add JwtRestrictedApplication check to XBlock callback

---

lms/djangoapps/ccx/apps.py

https://agile-jira.pearson.com/browse/PADV-1018
As 1018 describes, right now none of the CCXs are updating their outline when the outline on their corresponding master course is changed. The way it should work is, whenever the outline of a course is updated in studio, it emits the signal "course_published" and this signal should be captured by the CCX app and should update all children CCX for that course, however because the CCX app is not installed in Studio, this causes the course_published signal to not be aware of the receivers in the CCX app. Also the CCX app does not have an apps.py and thus cannot "export" the signal. This PR aims to add an apps.py to the CCX app.
- Add apps.py to lms.djangoapps.ccx and import the signals.
- Setup devstack.
- Create a course with CCX enabled.
- …

PADV 1018 - Changes to primary course not being reflected in the CCXs

---

lms/djangoapps/ccx/views.py

We need to migrate our implementation of course_operations features to openedx supported technologies such as events and filters. For that, we delete the run_extension_point related to the creation of a course.
- Create a course in course_operations

PADV-1019 - Delete run_extension_point in course_operations

---

lms/djangoapps/grades/rest_api/v1/gradebook_views.py

https://agile-jira.pearson.com/browse/PADV-1134
Right now, only course staff and course instructors are able to access the gradebook of a CCX, there is a requirement of allowing global staffs to access the gradebook too, since per business logic, every permission a course staff has, global staffs should also have those permissions. This PR aims to add the capacity to global staffs to access to the gradebook of a ccx.
- Setup devstack
- Checkout to this branch
- Create a CCX (licensed or not)
- Verify the access to the gradebook with a global staff (turn on the is_staff attribute of the user)

PADV 1134 - Global staff and superusers should have access to the CCX gradebook.

---

requirements/constraints.txt
requirements/edx/base.txt
requirements/edx/development.txt

https://agile-jira.pearson.com/browse/PADV-1270
This PR aims to update the openedx-events version from 8.3.0 to 9.10.0. The change was made manually since compiling it causes an error and fixing it requires a bigger effort. A new PR will be opened to solve the issue.
- Setup devstack
- Checkout to this branch
- Run `make requirements` inside of a lms shell
- Run `pip list`, openedx-events should be in the version 9.10.0.

feat: Installing new openedx-events version and fixing requirements

---

lms/djangoapps/grades/event_utils.py
lms/djangoapps/grades/events.py

https://agile-jira.pearson.com/browse/PADV-1276
This PR aims to add the changes made by Racoongang to our edx-platform repository. These changes include adding the following openedx-events triggers:
- `COURSE_PASSING_STATUS_UPDATED`
- `CCX_COURSE_PASSING_STATUS_UPDATED`
Cherrypick the follwing commits from the branch aci.main on https://github.com/raccoongang/edx-platform.
- https://github.com/raccoongang/edx-platform/pull/2552
- https://github.com/raccoongang/edx-platform/pull/2535
- https://github.com/raccoongang/edx-platform/pull/2533
- https://github.com/raccoongang/edx-platform/pull/2531
- https://github.com/raccoongang/edx-platform/pull/2529
- https://github.com/raccoongang/edx-platform/pull/2527
- https://github.com/raccoongang/edx-platform/pull/2526
- …

PADV 1276 - Move edx-platform changes to our repository

---

cms/envs/common.py
cms/envs/production.py
lms/envs/common.py
lms/envs/production.py

https://agile-jira.pearson.com/browse/PADV-1346
This PR aims to add the changes made in upstream to our edx-platform repository in order for Event Bus to work with the Credly project integration. Changes add:
-  'openedx_events' to `INSTALLED_APPS` from LMS common settings.
- `EVENT_BUS_PRODUCER_CONFIG` definition and configuration for lms and cms.
-  `BADGES_ENABLED` feature to conditionally allow producing events defined within EVENT_BUS_PRODUCER_CONFIG setting.
- `EVENT_BUS_PRODUCER_CONFIG` to `KEYS_WITH_MERGED_VALUES`
- `merge_producer_config` to lms production settings to combine with any env settings if any.
Cherrypick the follwing commits from upstream https://github.com/openedx/edx-platform:
- https://github.com/openedx/edx-platform/pull/33392
- …

PADV-1346: Backport edx-platform changes needed for Event Bus to work on our olive instance.

---

lms/djangoapps/instructor/enrollment.py

This PR adds the enrollment filter into CourseENrollmentAllowed to apply license enforcement when a license reach the purchased seats.
- https://github.com/Pearson-Advance/course_operations/pull/229
- Start openedx services with course operation and license enforcement
- Create institution, institution admin and a license with 0 purchased seats
- Add the following setting in lms/envs/common.py
```
OPEN_EDX_FILTERS_CONFIG = {
"org.openedx.learning.course.enrollment.started.v1": {
"fail_silently": False,
"pipeline": [
"pearson_course_operation.pipeline.EnforceLicense",
]
},
}
```
- Create a CCX created from the master course of the license created.
- Try to Enroll a student or Pending  student, using the institution portal being Global Admin and Institution Admin. Using  the instructor …

feat: add filter in CourseEnrollmentAllowed.

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

This PR updates the py2neo requirement to be able to build the openedx image using tutor.
- https://discuss.openedx.org/t/missing-py2neo-package-causing-build-issues-in-all-edx-platform-releases/11371
- https://discuss.openedx.org/t/error-no-matching-distribution-found-for-py2neo-2021-2-3/11631
- https://github.com/openedx/edx-platform/pull/33468

chore: update py2neo version.

---

common/djangoapps/third_party_auth/pipeline.py
lms/envs/common.py

This PR adds a new setting called: SAML_IES_ENTITIES_IDS to configure the values of the IES SAML IDP ids for stage and prod. Initially we avoided this approach, but due to some problems with the IES configuration, it is better to do it this way so that we can quickly change the values in case we need to change them.
- Set up a local SAML IDP, check this video about SAML and configuring a local IDP: https://youtu.be/1PoWSVtwheI
- Create a test account on the IDP, follow this: https://github.com/kenchan0130/docker-simplesamlphp?tab=readme-ov-file#customize-idp-users
- Remove the fullname attribute associated with the IDP user.
- Add the entity id uri to the list of: SAML_IES_ENTITIES_IDS
- In a private window, log in using the local IDP.
- You should be logged in automatically and the …

PADV-1511 - Add setting to store SAML IDP id values.

---

openedx/core/djangoapps/user_authn/views/registration_form.py

- https://agile-jira.pearson.com/browse/PADV-1556
Change REGISTRATION_EXTENSION_FORM platform setting and turns it into a site awareness feature
This feature could be fully tested along with https://github.com/Pearson-Advance/pearson-core/pull/53 
Nonetheless, you could follow the next steps to test it into the platform:
- Simply set the REGISTRATION_EXTENSION_FORM key into the the site configurations of a enabled site into your edx-platform instance with a string based value
- Place a debugger and/or print statement of its value 
- Access to the registration form of the affected site and confirms that the setting is being pulled

PADV-1556 Create custom form for registration extra fields.

---

lms/templates/courseware/courseware-chromeless.html

This PR adds a fix to the courseware-chromeless.html template, this template is used to render the XBlock on the learning MFE in an Iframe, this template contains a JavaScript code that sends a postMessage to the parent window that is used by the learning MFE to resize the Iframe to the heigth of its content, on the initial load of the Iframe the height is incorrectly calculated when the maintenance banner is added to the unit content, to fix this an extra 250px is added to the calculated height of the Iframe.

fix: courseware-chromeless.html iframe height

---

lms/static/js/edxnotes/plugins/llm_summarize.js
lms/static/js/edxnotes/views/notes_factory.js

This PR is part of the AI assistance project and aims to add the annotatorjs plugin that adds a button to summarize a selected text inside a text or HTML block.
- Setup devstack and pull changes.
- Select a text inside a text or HTML block.
- A new button should appear to summarize the text.
- The button, when clicked should open the annotations modal.

PADV 1580 - Create annotatorjs plugin for AI select and summarize

---

lms/djangoapps/edxnotes/decorators.py
lms/static/js/edxnotes/plugins/llm_summarize.js
lms/static/js/edxnotes/views/notes_factory.js

This PR is part of the AI assistance project and aims to add the connection to the summarize backend to the annotator js llm_summarize plugin. The plugin sends a request to pearson core summarize api and replaces the annotation text area value with the summary.
- Setup devstack and pull changes.
- Setup edx notes api service.
- Setup Pearson core plugin
- Follow instructions to enable LLM summarize endpoint in pearson core.
- Enable the waffle switch 'pearson_core.llm_summarize.enable_llm_summarize'
- On studio, select a course, go to advance settings, and on the 'other course settings field' put the following JSON:
```json
{
"llm_summarize": {
"is_enabled": true
}
}
```
- Select a text inside a text or HTML block.
- Click on the summarize button.
- A loader should appear indicating that …

PADV 1684 - Add feature flag for LLM summarize for frontend

---

lms/djangoapps/edxnotes/decorators.py
lms/static/js/edxnotes/plugins/llm_summarize.js
lms/static/js/edxnotes/views/notes_factory.js

This PR is part of the AI assistance project and aims to add the connection to the summarize backend to the annotator js llm_summarize plugin. The plugin sends a request to pearson core summarize api and replaces the annotation text area value with the summary.
- Setup devstack and pull changes.
- Setup edx notes api service.
- Select a text inside a text or HTML block.
- Click on the summarize button.
- A loader should appear indicating that the content is being summarized.
- The text area to save the annotation should contain the summarized content.

PADV 1584 - Add summarize functionality to plugin

---

lms/static/js/edxnotes/plugins/llm_summarize.js

https://github.com/Pearson-Advance/pearson-core/tree/vue/PADV-1593
This PR is part of the AI assistance project and aims to add style and responsiveness to the the annotation textbox in order to improve the UX of users who read the summarized text .
- Setup devstack and pull changes.
- Setup edx notes api service.
- Setup Pearson core plugin
- Follow instructions to enable LLM summarize endpoint in pearson core.
- Enable the waffle switch 'pearson_core.llm_summarize.enable_llm_summarize'
- On studio, select a course, go to advance settings, and on the 'other course settings field' put the following JSON:
```json
{
"llm_summarize": {
"is_enabled": true,
"summarization_prompt": "Some base prompt here"
}
}
```
- Select a text inside a text or HTML block.
- Click on the summarize button.

PADV-1593: Expand Annotation Textbox

---

lms/static/js/edxnotes/views/notes_factory.js

The llm_summarize plugin was added again in a conflict as a default plugin of annotatorjs, this causes that the plugin cannot be activated or deactivated. This PR aims to fix this issue

PADV 1853 - Fix LLM summarize feature flag not working

---

lms/templates/courseware/courseware-chromeless.html

https://github.com/Pearson-Advance/pearson-core/tree/vue/PADV-1871
This PR is part of the AI assistance project and aims to fix annotator's modal resizer behaviour to work properly.
- Setup devstack and pull changes on edx-platform from this branch.
- Run `make dev.static.lms`  in the Devstack workspace. 
- Setup edx notes api service.
- Enable notes for a course,
- Select a text inside from the course content.
- Click on the notes button.
- Resize the modal.

PADV-1871: correct resizer behavior in annotator modal

---

openedx/core/djangoapps/user_authn/views/registration_form.py

- https://agile-jira.pearson.com/browse/PADV-2086
This PR allows the sites to request the username field when a SSO or third party auth integration is set. This is allowed by overriding the username value to None so in that way the workflow won't apply the `hidden` property to the field in registration form. 
[x] Change third_party_authvalidation workflow to set "None" whatever the third part auth system is sending into the username during the registration process
[x] This PR also removes the changes made in this PR https://github.com/Pearson-Advance/edx-platform/pull/129/files
1. Set up a valid SAML IdP in your workspace, set up your devstack instance following the openedx guide https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/index.ht …

PADV-2086 Allow username field to be shown on SAML registration process

---

lms/djangoapps/courseware/module_render.py

- https://agile-jira.pearson.com/browse/PADV-2022
This PR adds the feature to set via site configurations the maximum file size to be accepted for the attachments to be uploaded by a Xblock handler. If not limit has been set, it would take the one set by the platform as it used to do.
[x] Pull the STUDENT_FILEUPLOAD_MAX_SIZE site configurations and checks if the file size metts the criteria
[x] Set the file size defined either by site configurations or platform setting
1. Set the site configuration as `STUDENT_FILEUPLOAD_MAX_SIZE': 1400000000` where 1400000000 is a byte expressed value of the desire max size. In this case is ~1.4GB. 
2. Confirms that the platform allows upload files with a size less than the defined 1.4GB limit and it only impacts for the Xblock mentioned.
This has been …

PADV-2022 set STUDENT_FILEUPLOAD_MAX_SIZE via site configurations

---

openedx/core/djangoapps/oauth_dispatch/jwt.py

This PR adds a new filter that updates the JWT token's payload of a User by adding extra data when its creation is requested. The filter receives the payload and the User object, and returns the User and the modified payload with any new data included. For example: adds a new field with the permission roles of a certain subproject. Other uses could include: adding the last access datetime of the User, a status, or any other useful information related to the User.
For this particular change, the call of the filter is implemented in the `_create_jwt` method when requesting the corresponding token.

PADV-2127 - Add SessionJWTCreationRequested filter call.

---

lms/templates/instructor/edx_ace/allowedenroll/email/body.html
lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

This pull request updates the login button alignment and layout in email templates to ensure proper rendering across all major email clients. The button is now consistently aligned to the right using a table-based layout, which improves compatibility especially in clients like Gmail and Outlook. Additionally, inline styles were preserved and refined to match the existing branding and accessibility standards.
- Refactored the Log In and Register buttons to use a table wrapper with align="right" for proper alignment in email clients.
- Removed reliance on text-align inside <td> and instead used table layout for safer positioning.
- Ensured inline styles maintain the original visual appearance, including background color, padding, and font styles.

PADV-2235 fix: CSS style to email templates to make them compatible with email."

---

lms/templates/instructor/edx_ace/allowedenroll/email/body.html
lms/templates/instructor/edx_ace/enrollenrolled/email/body.html
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

This PR introduces a new background image (`IPbackground.png`) to be used in enrollment notification emails. The previous image, an `.svg`, was not rendering correctly across several email clients — especially Gmail — due to limited support for vector images in HTML emails.
To ensure better compatibility and consistent branding, the `.svg` has been replaced by a `.png` version of the same asset, hosted in the same static path.
- Install and configure openedx-themes (if you don't have it):
-  Clone the openedx-themes repository into the same directory where the src folder is located.
- Switch to this branch of the themes repository:
- https://github.com/Pearson-Advance/openedx-themes/pull/276 
- Open the LMS shell.
- Navigate to edx/etc.
- Edit the lms.yml file and add the following …

PADV-2313 fix: Import a new .png background image to the enroll email

---

lms/envs/common.py
openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

This PR includes  improvements to the email templates used in enrollment communications and deleting unnecessary configs (moved to pearson plugin) 
- Ensures the main email container (<table>) uses width: 100% to properly adapt across email clients and prevent overflow or layout issues.
- Adds a new informational link to the footer section:
https://www.pearsonvue.com/us/en/training-centers/skilling-suite.html
This link directs users to the Skilling Suite informational page for more context and support.
- Moving configs to pearson plugin

PADV-2314 fix: Modify styles to adapt the container of enroll email with the email client

---

openedx/core/djangoapps/ace_common/templates/ace_common/edx_ace/common/base_body.html

This PR applies a max-width to the content container to center the content.
- Adds a max-width into the main container and applies a margin auto to center it.

PADV-2314 fix: Modify styles to adapt the container of enroll email with the email client (recommended max-width approach).
